### ISSUE TITLE
HTML Output doesn't include filename

### ISSUE THREAD

**Issue by ThePixelDeveloper** [robotis/PHPLinter#1]
As seen here

![](http://i.imgur.com/TRT2t.png)

It might be worth adding table headers; A table full of numbers is confusing.

**Comment by robotis** [comment]
Hmm there seems to be some wierdness regarding '~'. if you direct the linter to a full path '/home/mathew...' ect. It should work.

I'll look into it.

**Comment by robotis** [comment]
This is now fixed in trunk
