### ISSUE TITLE
Unreachable code behaviour

### ISSUE THREAD

**Issue by ThePixelDeveloper** [robotis/PHPLinter#2]
```
<?php defined('SYSPATH') or die('No direct script access.');

return array
(
    'database' => array
    (
        'encrypted' => TRUE
    )
);
```

I get the error 

> Unreachable code on line 3

for this PHP file. It doesn't understand you can return from a PHP file and have access to that return data in another file.

**Comment by robotis** [comment]
Fix in trunk
